version: '3.7'

services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - monitoring-network

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    restart: unless-stopped
    volumes:
      - ./clickhouse/tables/pinba.requests.sql:/docker-entrypoint-initdb.d/pinba.requests.sql
    networks:
      - monitoring-network

  pinba:
    build: ./pinba
    container_name: pinba
    hostname: pinba
    restart: unless-stopped
    ports:
      - "30002:30002/udp"
    command: bash -c "cd /opt/pinba-server/ && /usr/bin/php workerman_clickhouse.php start"
    tty: true
    networks:
      - monitoring-network

  pinba_client:
    build: ./pinba_client
    container_name: pinba_client
    hostname: pinba_client
    restart: unless-stopped
    volumes:
      - ./app/:/var/www/
      - ./pinba_client/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "13131:80"
    networks:
      - monitoring-network

networks:
    monitoring-network:
        driver: bridge
